apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-staging
  template:
    metadata:
      labels:
        app: myapp-staging
    spec:
      containers:
        - name: myapp-staging
          image: myacrregistry12.azurecr.io/mytestapp:staging  # Use staging image
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-staging-service
spec:
  selector:
    app: myapp-staging
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000